name: 'Sync Diigo Highlights to Readwise'
author: 'Dexter St Pierre'
description: 'A workflow to sync your highlights from Diigo to Readwise'
inputs:
  diigoApiKey:
    default: ${{ secrets.DIIGO_API_KEY }}
  diigoUsername:
    default: ${{ secrets.DIIGO_USERNAME }}
  diigoPassword:
    default: ${{ secrets.DIIGO_PASSWORD }}
  readwiseToken:
    default: ${{ secrets.READWISE_TOKEN }}
runs:
  using: 'node12'
  main: 'dist/main.js'