name: 'Sync Diigo Highlights to Readwise'
author: 'Dexter St Pierre'
description: 'A workflow to sync your highlights from Diigo to Readwise'
inputs:
  diigoApiKey:
    description: "Key used to access Diigo API"
    required: true
  diigoUsername:
    description: "Username used to login to your Diigo account"
    required: true
  diigoPassword:
    description: "Password used to login to your Diigo account"
    required: true
  readwiseToken:
    description: "Token used to access Readwise API"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'